    - name: Install Apache
      yum:
        name: httpd
        state: latest

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Install MySQL
      yum:
        name: mysql-server
        state: latest

    - name: Start MySQL service
      service:
        name: mysqld
        state: started
        enabled: true

    - name: Install PHP
      yum:
        name: php
        state: latest

    - name: Install PHP MySQL module
      yum:
        name: php-mysqlnd
        state: latest

    - name: Copy PHP test page
      copy:
        content: "<?php phpinfo(); ?>"
        dest: /var/www/html/index.php

    - name: Enable HTTP port in firewall
      firewalld:
        port: "{{ http_port }}/tcp"
        permanent: true
        state: enabled
        immediate: true
